name: CapturePlugin
version: '1.0-SNAPSHOT'
main: org.showlee.capturePlugin.CapturePlugin
api-version: '1.20'
commands:
  capture:
    description: Управление системой захвата точек
    usage: /capture [инфо]
